;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; 3DDEMO.INC

BITMAP_OFF      .equ    16              ; In bytes
PPP             .equ    4               ; Pixels per Phrase             

BMP_WIDTH       .equ    320
BMP_PHRASES     .equ    160
BMP_CLIP        .equ    80
BMP_HEIGHT      .equ    200
BMP_LINES       .equ    (BMP_HEIGHT*2)

LISTSIZE        .equ    5               ; In phrases
